apiVersion: v1
kind: PersistentVolume
metadata:
  name: mydata-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/hossam/Documents/mongo-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mydata-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi