kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: keda-role
  namespace: keda
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - pods
  - deployments
  - replicasets
  - horizontalpodautoscalers
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: keda-role-binding
  namespace: keda
subjects:
- kind: ServiceAccount
  name: keda
  namespace: keda
roleRef:
  kind: Role
  name: keda-role
  apiGroup: rbac.authorization.k8s.io

